# -*- coding: utf-8 -*-
"""Multi_Class CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n3dCV8SJkPCbhY8vp6RDUT7JX41NBhjb

# Multi-Class classification by CNN

### Import required libraries
"""

# Import required libraries
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models, callbacks
import matplotlib.pyplot as plt

"""### Step 1: Data Preparation"""

# -------------------------------
# Step 1: Data Preparation
# -------------------------------

# Training data generator with augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,               # Normalize pixel values
    rotation_range=20,            # Random rotation
    width_shift_range=0.2,        # Horizontal shift
    height_shift_range=0.2,       # Vertical shift
    horizontal_flip=True,         # Horizontal flip
    zoom_range=0.2                # Random zoom
)

# Test data generator without augmentation
test_datagen = ImageDataGenerator(rescale=1./255)

# Load training data from directory
train_generator = train_datagen.flow_from_directory(
    'cifar10_data/train',
    target_size=(32, 32),
    batch_size=64,
    class_mode='categorical',
    shuffle=True
)

# Load test data from directory
test_generator = test_datagen.flow_from_directory(
    'cifar10_data/test',
    target_size=(32, 32),
    batch_size=64,
    class_mode='categorical',
    shuffle=False  # This is critical!
)

print(list(train_generator.class_indices.keys()))

"""### Step 2: Build CNN Model"""

# -------------------------------
# Step 2: Build CNN Model
# -------------------------------

# Define the model using Sequential API with explicit Input layer
model = models.Sequential([
    tf.keras.Input(shape=(32, 32, 3)),  # Explicit input layer, Input image size 32X32 with 3 channels (RGB)

    # First block
    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(), #Stabilizes Learning
    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.3),

    # Second block
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.4),

    # Third block
    layers.Conv2D(256, (3, 3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.5),

    # Fully connected layers
    layers.Flatten(),

    # Replace Flatten with GlobalAveragePooling2D
    #layers.GlobalAveragePooling2D(),

    layers.Dense(512, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')  # Output layer for 10 classes
])

# Compile the model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

"""### Step 3: Define Callbacks

#### Role of ReduceLROnPlateau

- This callback watches val_loss.

- If val_loss does not go down for patience epochs (in your case, 3), it reduces the learning rate.

- Lower learning rate → smaller weight updates → gives the optimizer a chance to fine‑tune instead of bouncing around.

- Often, after the learning rate is reduced, you’ll see val_loss go down again.
"""

# Step 3: Define Callbacks
# -------------------------------
from tensorflow.keras.callbacks import ModelCheckpoint

# Stop training early if validation accuracy stops improving
# Wait for 5 epochs after the last improvement before stopping.
early_stop = callbacks.EarlyStopping(patience=5, restore_best_weights=True)

# Save the best model during training
checkpoint = ModelCheckpoint(
    'best_model.keras',
    monitor='val_accuracy',
    save_best_only=True,
    mode='max',         # 'max' because higher accuracy is better
    verbose=0
)

callback = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,       # reduce LR by half
    patience=3,       # wait 3 epochs before reducing
    min_lr=1e-6       # lower bound
)

"""### Step 4: Adjust weights for poorly detected classes"""

# Step 4: Adjust weights for poorly detected classes
# -------------------------------

# Get class indices
class_indices = train_generator.class_indices
print("Class indices:", class_indices)

# Assign extra weight to 'cat' and 'dog' as model is not properly detecting these two!
# Create default weights for all classes (initially set to 1.0 for each class)
my_class_weight = {i: 1.0 for i in range(len(class_indices))}

# Increase the weight for the 'cat' class to emphasize its importance during training
my_class_weight[class_indices['cat']] = 1.5
# Increase the weight for the 'dog' class to emphasize its importance during training
my_class_weight[class_indices['dog']] = 1.5

print("Class weights:", my_class_weight)

"""### Step 5: Train the model"""

# Step 5: Train the model
# -------------------------------

# Train the model with training and validation data
history = model.fit(
    train_generator,
    epochs=50,
    validation_data=test_generator,
    class_weight = my_class_weight,
    verbose=1,
    callbacks=[early_stop, checkpoint,callback]   # e.g., ReduceLROnPlateau or LearningRateScheduler
)

# Example: find epoch with lowest validation loss
import numpy as np

val_loss = history.history['val_loss']
best_epoch = np.argmin(val_loss) + 1   # +1 because epochs are 1-indexed
print("Best epoch based on val_loss:", best_epoch)

"""### Step 6: Classification Report"""

# Step 6: Classification Report
# -------------------------------

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

# Assuming you already have a trained model and test_generator
# Example:
# model = keras.models.load_model('your_model.h5')
# test_generator = test_datagen.flow_from_directory(...)

# Step 1: Predict on test data
y_pred_probs = model.predict(test_generator, steps=test_generator.samples // test_generator.batch_size + 1)
y_pred = np.argmax(y_pred_probs, axis=1)

# Step 2: Get true labels
y_true = test_generator.classes

# Step 3: Get class names
class_names = list(test_generator.class_indices.keys())

# Step 4: Print classification report
print("Classification Report:\n")
print(classification_report(y_true, y_pred, target_names=class_names))

# Step 5: Plot confusion matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix')
plt.tight_layout()
plt.show()

"""### Step 7: Plot Accuracy and Loss"""

# -------------------------------
# Step 7: Plot Accuracy and Loss
# -------------------------------

# Plot training and validation accuracy
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Plot training and validation loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""# Execute following code only to reuse the model for prediction

### Step 8: Predict and display image
"""

# Step 8: Predict and display image
# -------------------------------

# Import libraries
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
from keras.models import load_model

# Load the trained model
model = load_model('best_model.keras')

# Load class names from training generator (you must define this once during training)
#class_names = list(train_generator.class_indices.keys())
class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']


def predict_image(image_path):
    # Load and preprocess image
    img = image.load_img(image_path, target_size=(32, 32))
    img_array = image.img_to_array(img)
    img_array = img_array / 255.0
    img_batch = np.expand_dims(img_array, axis=0)

    # Predict
    result = model.predict(img_batch)
    predicted_class = np.argmax(result)
    confidence = round(result[0][predicted_class] * 100, 2)
    prediction = class_names[predicted_class]

    # Print prediction
    print(f"\n🖼️ Image: {image_path}")
    print(f"Predicted Class: {prediction}, Confidence: {confidence}%")

    print("\nClass Probabilities:")
    for i, class_name in enumerate(class_names):
        prob = round(result[0][i] * 100, 2)
        print(f"{class_name}: {prob}%")

    # Display image with smaller size
    plt.figure(figsize=(1, 1))  # Smaller display size
    plt.imshow(img)
    plt.title(f"{prediction} ({confidence}%)")
    plt.axis('off')
    plt.show()


# Example usage
predict_image('cifar10_data/single_prediction/12.png')
predict_image('cifar10_data/single_prediction/227.png')
predict_image('cifar10_data/single_prediction/231.png')
predict_image('cifar10_data/single_prediction/145.png')
predict_image('cifar10_data/single_prediction/72.png')
predict_image('cifar10_data/single_prediction/38.png')
predict_image('cifar10_data/single_prediction/238.png')
predict_image('cifar10_data/single_prediction/frog777.png')
predict_image('cifar10_data/single_prediction/dog_777.png')
predict_image('cifar10_data/single_prediction/horse_777.png')
predict_image('cifar10_data/single_prediction/horse_999.png')

"""# Well Done!"""